### ISSUE TITLE
Support Casbin as the authorization module

### ISSUE THREAD

**Issue by hsluoyz** [quilt/quilt#932]
Hi, [Casbin](https://github.com/casbin/casbin) is an authorization library that supports models like ACL, RBAC, ABAC.

Related to RBAC, Casbin has several advantages:
1. roles can be cascaded, aka roles can have roles.
2. support resource roles, so users have their roles and resource have their roles too. role = group here.
3. the permission assignments (or policy in Casbin's language) can be persisted in files or database (MySQL and Cassandra).

And you can even customize your own access control model, for example, mix RBAC and ABAC together by using roles and attributes at the same time. It's very flexible.

Casbin can provide more flexibility and security than the current ACL. I can make PR if needed. Let me know if there's any question:) Thanks.

**Comment by ejj** [comment]
Thanks for the suggestion @hsluoyz!  Casbin looks like a cool project, congrats!

I suppose the primary question I would have, is this.  From the user's perspective, what does Casbin do for them?  Is there any functionality in Quilt that would become easier for a user if we adopted it?  Are there any important features that are hard to implement without it?  I would want to have a better understanding of its impact on the overall project before integrating it.

**Comment by hsluoyz** [comment]
Hi @ejj , I looked at the code, but do not understand the ACL in quilt very well. This will help my evaluation of applying Casbin on quilt. The ACL is defined as:

```go
type ACL struct {
	ID int

	Admin            []string
	ApplicationPorts []PortRange
}
```

``Admin`` seems to be a IP list. ``ApplicationPorts`` is a port list? Then the ACL is a firewall rule I think? But I don't know who this firewall rule restricts? And I didn't see the enforcement logic for the ACL.

**Comment by ejj** [comment]
So Quilt has two places where it enforces ACLs.  First it can be used to setup virtual machines in a cloud provider (i.e. Amazon EC2), the ACL struct you're showing there represents the cloud provider security groups for the VMs that quilt sets up.  I.E. it restricts what IP addresses are allowed to contact those virtual machines.

Secondly, Quilt also can enforce a strict firewall between containers that it boots on those virtual machines.  This is represented in the database table "Connection" in db/connection.go.

I'd be happy to help you work out how to apply the changes, but I think before that it's important to think about what benefit there would be to users if we did so.  I don't want to accept a new dependency in the project unless there's a clear problem that it solves for users.  At this point, it's not entirely clear to me what precisely Casbin is, and what benefit it would have for a project like Quilt.  Would you please describe in a bit more detail?  That way we could make a decision about whether or not it makes sense to proceed before you put a lot of effort into implementation.

**Comment by hsluoyz** [comment]
> So Quilt has two places where it enforces ACLs. First it can be used to setup virtual machines in a cloud provider (i.e. Amazon EC2), the ACL struct you're showing there represents the cloud provider security groups for the VMs that quilt sets up. I.E. it restricts what IP addresses are allowed to contact those virtual machines.

So this ACL is actually enforced by Amazon EC2 instead of quilt. Casbin can be better to be used as an enforcement module, which means that quilt should be the server-side to be able to enforce the policy rules and determine who can access what. Since this ACL is only used by EC2, there's not much Casbin can do indeed.

> Secondly, Quilt also can enforce a strict firewall between containers that it boots on those virtual machines. This is represented in the database table "Connection" in db/connection.go.

If this firewall rule is enforced by quilt, I think it can be replaced by Casbin.

> I'd be happy to help you work out how to apply the changes, but I think before that it's important to think about what benefit there would be to users if we did so.

For firewall rules, it seems that you can't use features like RBAC, ABAC. I'm unclear too for the possible improvement by using it. So I will close this for now.
